[target.'cfg(target_arch="wasm32")']
runner = "wasm-bindgen-test-runner"
rustflags = [
	# Workaround for wasm-bindgen duplicate function declarations with v0 mangling
	# see https://github.com/rustwasm/wasm-bindgen/issues/4820
	"-Csymbol-mangling-version=legacy",
	"-Zunstable-options",
]